language: csharp
solution: Hotsapi.Parser.sln
mono: none
dotnet: 2.0.0
script:
- dotnet test -c Debug Hotsapi.Parser.Test/Hotsapi.Parser.Test.csproj
- dotnet publish --configuration=Release
- tar -czf parser.tar.gz -C Hotsapi.Parser/bin/Release/netcoreapp2.0/publish .

addons:
  artifacts:
    s3_region: "eu-west-1"
    bucket: hotsapi-public
    target_paths: Hotsapi.Parser/$TRAVIS_BRANCH$TRAVIS_PULL_REQUEST_BRANCH/$TRAVIS_JOB_NUMBER:Hotsapi.Parser/$TRAVIS_BRANCH$TRAVIS_PULL_REQUEST_BRANCH/latest
    paths:
      - parser.tar.gz

cache:
  directories:
    - $HOME/.nuget
